# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(647, 173)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("* {\n"
"    background-color: rgb(24, 26, 40);\n"
"}\n"
"QLabel {\n"
"    background-color: rgb(24, 26, 40);\n"
"}\n"
"QLabel:hover {\n"
"    background-color: rgb(87, 95, 145);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.recordButton = QtWidgets.QLabel(self.centralwidget)
        self.recordButton.setGeometry(QtCore.QRect(510, 40, 101, 91))
        self.recordButton.setText("")
        self.recordButton.setPixmap(QtGui.QPixmap("record.png"))
        self.recordButton.setAlignment(QtCore.Qt.AlignCenter)
        self.recordButton.setObjectName("recordButton")
        self.pauseButton = QtWidgets.QLabel(self.centralwidget)
        self.pauseButton.setEnabled(False)
        self.pauseButton.setGeometry(QtCore.QRect(380, 40, 101, 91))
        self.pauseButton.setText("")
        self.pauseButton.setPixmap(QtGui.QPixmap("pause.png"))
        self.pauseButton.setAlignment(QtCore.Qt.AlignCenter)
        self.pauseButton.setObjectName("pauseButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Screen Reader"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
