# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("* {\n"
"    background-color: rgb(24, 26, 40);\n"
"    color: rgb(174, 176, 190);\n"
"}\n"
"QLabel {\n"
"    background-color: rgb(24, 26, 40);\n"
"}\n"
"QLabel:hover {\n"
"    background-color: rgb(87, 95, 145);\n"
"}\n"
"QPushButton {\n"
"    border: 1px solid rgb(174, 176, 190);\n"
"    border-radius: 15px;\n"
"    background-color: rgb(24, 26, 40);\n"
"    color: rgb(174, 176, 190);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid rgb(174, 176, 190);\n"
"    border-radius: 15px;\n"
"    background-color: rgb(87, 95, 145);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.recordButton = QtWidgets.QLabel(self.centralwidget)
        self.recordButton.setGeometry(QtCore.QRect(520, 10, 101, 91))
        self.recordButton.setText("")
        self.recordButton.setPixmap(QtGui.QPixmap("record.png"))
        self.recordButton.setAlignment(QtCore.Qt.AlignCenter)
        self.recordButton.setObjectName("recordButton")
        self.pauseButton = QtWidgets.QLabel(self.centralwidget)
        self.pauseButton.setEnabled(False)
        self.pauseButton.setGeometry(QtCore.QRect(390, 10, 101, 91))
        self.pauseButton.setStyleSheet("")
        self.pauseButton.setText("")
        self.pauseButton.setPixmap(QtGui.QPixmap("pause.png"))
        self.pauseButton.setAlignment(QtCore.Qt.AlignCenter)
        self.pauseButton.setObjectName("pauseButton")
        self.videopathLabel = QtWidgets.QLabel(self.centralwidget)
        self.videopathLabel.setGeometry(QtCore.QRect(10, 20, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.videopathLabel.setFont(font)
        self.videopathLabel.setStyleSheet("* {\n"
"    color: rgb(174, 176, 190);\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.videopathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videopathLabel.setObjectName("videopathLabel")
        self.videopathEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.videopathEdit.setGeometry(QtCore.QRect(10, 50, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.videopathEdit.setFont(font)
        self.videopathEdit.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.videopathEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.videopathEdit.setObjectName("videopathEdit")
        self.videopathButton = QtWidgets.QPushButton(self.centralwidget)
        self.videopathButton.setEnabled(True)
        self.videopathButton.setGeometry(QtCore.QRect(250, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.videopathButton.setFont(font)
        self.videopathButton.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.videopathButton.setObjectName("videopathButton")
        self.videoformatLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoformatLabel.setGeometry(QtCore.QRect(10, 190, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.videoformatLabel.setFont(font)
        self.videoformatLabel.setStyleSheet("* {\n"
"    color: rgb(174, 176, 190);\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.videoformatLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoformatLabel.setObjectName("videoformatLabel")
        self.videoformatEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.videoformatEdit.setGeometry(QtCore.QRect(130, 180, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.videoformatEdit.setFont(font)
        self.videoformatEdit.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.videoformatEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.videoformatEdit.setObjectName("videoformatEdit")
        self.videofilenameLabel = QtWidgets.QLabel(self.centralwidget)
        self.videofilenameLabel.setGeometry(QtCore.QRect(110, 100, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.videofilenameLabel.setFont(font)
        self.videofilenameLabel.setStyleSheet("* {\n"
"    color: rgb(174, 176, 190);\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.videofilenameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videofilenameLabel.setObjectName("videofilenameLabel")
        self.videofilenameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.videofilenameEdit.setGeometry(QtCore.QRect(10, 130, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.videofilenameEdit.setFont(font)
        self.videofilenameEdit.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.videofilenameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.videofilenameEdit.setObjectName("videofilenameEdit")
        self.mousescriptLabel = QtWidgets.QLabel(self.centralwidget)
        self.mousescriptLabel.setGeometry(QtCore.QRect(130, 230, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mousescriptLabel.setFont(font)
        self.mousescriptLabel.setStyleSheet("* {\n"
"    color: rgb(174, 176, 190);\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.mousescriptLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mousescriptLabel.setObjectName("mousescriptLabel")
        self.mousescriptText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.mousescriptText.setGeometry(QtCore.QRect(10, 260, 351, 201))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mousescriptText.setFont(font)
        self.mousescriptText.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.mousescriptText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mousescriptText.setPlainText("")
        self.mousescriptText.setObjectName("mousescriptText")
        self.xLabel = QtWidgets.QLabel(self.centralwidget)
        self.xLabel.setGeometry(QtCore.QRect(390, 130, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xLabel.setFont(font)
        self.xLabel.setStyleSheet("* {\n"
"    color: rgb(174, 176, 190);\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.xLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xLabel.setObjectName("xLabel")
        self.yLabel = QtWidgets.QLabel(self.centralwidget)
        self.yLabel.setGeometry(QtCore.QRect(490, 130, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yLabel.setFont(font)
        self.yLabel.setStyleSheet("* {\n"
"    color: rgb(174, 176, 190);\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.yLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yLabel.setObjectName("yLabel")
        self.xEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.xEdit.setGeometry(QtCore.QRect(410, 120, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xEdit.setFont(font)
        self.xEdit.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.xEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.xEdit.setObjectName("xEdit")
        self.yEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.yEdit.setGeometry(QtCore.QRect(510, 120, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yEdit.setFont(font)
        self.yEdit.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.yEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.yEdit.setObjectName("yEdit")
        self.whLabel = QtWidgets.QLabel(self.centralwidget)
        self.whLabel.setGeometry(QtCore.QRect(490, 180, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.whLabel.setFont(font)
        self.whLabel.setStyleSheet("* {\n"
"    color: rgb(174, 176, 190);\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.whLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.whLabel.setObjectName("whLabel")
        self.widthEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.widthEdit.setGeometry(QtCore.QRect(410, 170, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.widthEdit.setFont(font)
        self.widthEdit.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.widthEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.widthEdit.setObjectName("widthEdit")
        self.heightEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.heightEdit.setGeometry(QtCore.QRect(510, 170, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.heightEdit.setFont(font)
        self.heightEdit.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.heightEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.heightEdit.setObjectName("heightEdit")
        self.windowsBox = QtWidgets.QComboBox(self.centralwidget)
        self.windowsBox.setGeometry(QtCore.QRect(410, 230, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.windowsBox.setFont(font)
        self.windowsBox.setStyleSheet("border: 1px solid rgb(174, 176, 190);")
        self.windowsBox.setObjectName("windowsBox")
        self.windowsBox.addItem("")
        self.automoveLabel = QtWidgets.QCheckBox(self.centralwidget)
        self.automoveLabel.setGeometry(QtCore.QRect(410, 270, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.automoveLabel.setFont(font)
        self.automoveLabel.setStyleSheet("border-radius: 15px;")
        self.automoveLabel.setObjectName("automoveLabel")
        self.autocropLabel = QtWidgets.QLabel(self.centralwidget)
        self.autocropLabel.setGeometry(QtCore.QRect(440, 300, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.autocropLabel.setFont(font)
        self.autocropLabel.setStyleSheet("* {\n"
"    color: rgb(174, 176, 190);\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.autocropLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.autocropLabel.setObjectName("autocropLabel")
        self.autocropText = QtWidgets.QLineEdit(self.centralwidget)
        self.autocropText.setGeometry(QtCore.QRect(380, 330, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.autocropText.setFont(font)
        self.autocropText.setStyleSheet("border: 1px solid rgb(174, 176, 190);\n"
"border-radius: 15px;")
        self.autocropText.setAlignment(QtCore.Qt.AlignCenter)
        self.autocropText.setObjectName("autocropText")
        self.recordaudioLabel = QtWidgets.QCheckBox(self.centralwidget)
        self.recordaudioLabel.setGeometry(QtCore.QRect(410, 390, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recordaudioLabel.setFont(font)
        self.recordaudioLabel.setStyleSheet("border-radius: 15px;")
        self.recordaudioLabel.setChecked(False)
        self.recordaudioLabel.setObjectName("recordaudioLabel")
        self.audiospecLabel = QtWidgets.QCheckBox(self.centralwidget)
        self.audiospecLabel.setGeometry(QtCore.QRect(410, 420, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.audiospecLabel.setFont(font)
        self.audiospecLabel.setStyleSheet("border-radius: 15px;")
        self.audiospecLabel.setChecked(False)
        self.audiospecLabel.setTristate(False)
        self.audiospecLabel.setObjectName("audiospecLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Screen Reader"))
        self.videopathLabel.setText(_translate("MainWindow", "Video Path:"))
        self.videopathButton.setText(_translate("MainWindow", "Select!"))
        self.videoformatLabel.setText(_translate("MainWindow", "Video format:"))
        self.videoformatEdit.setText(_translate("MainWindow", "mp4"))
        self.videofilenameLabel.setText(_translate("MainWindow", "Video Name:"))
        self.videofilenameEdit.setText(_translate("MainWindow", "Output"))
        self.mousescriptLabel.setText(_translate("MainWindow", "Draw Script:"))
        self.xLabel.setText(_translate("MainWindow", "X:"))
        self.yLabel.setText(_translate("MainWindow", "Y:"))
        self.xEdit.setText(_translate("MainWindow", "0"))
        self.yEdit.setText(_translate("MainWindow", "0"))
        self.whLabel.setText(_translate("MainWindow", "X"))
        self.widthEdit.setText(_translate("MainWindow", "0"))
        self.heightEdit.setText(_translate("MainWindow", "0"))
        self.windowsBox.setItemText(0, _translate("MainWindow", "DISPLAY1"))
        self.automoveLabel.setText(_translate("MainWindow", "Auto Move"))
        self.autocropLabel.setText(_translate("MainWindow", "Auto Crop:"))
        self.autocropText.setText(_translate("MainWindow", "3x30x-3x-1"))
        self.recordaudioLabel.setText(_translate("MainWindow", "Record Audio"))
        self.audiospecLabel.setText(_translate("MainWindow", "Special Audio File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
